export const categories = [
  {
    name: 'Design',
    tools: [
      { name: 'Figma', link: '/figma' },
      { name: 'Sketch', link: '/sketch' },
      { name: 'Adobe XD', link: '/adobe-xd' },
      { name: 'Illustrator', link: '/illustrator' },
      { name: 'Photoshop', link: '/photoshop' },
      { name: 'InDesign', link: '/indesign' },
      { name: 'Lightroom', link: '/lightroom' },
      { name: 'After Effects', link: '/after-effects' },
      { name: 'Affinity Photo', link: '/affinity-photo' },
      { name: 'Framer', link: '/framer' },
      { name: 'InVision', link: '/invision' },
      { name: 'Miro', link: '/miro' },
      { name: 'Overflow.io', link: '/overflow.io' },
      { name: 'Principle', link: '/principle' },
    ],
  },
  {
    name: 'Development',
    tools: [
      { name: 'VS Code', link: '/vscode' },
      { name: 'Sublime Text', link: '/sublime' },
      { name: 'Atom', link: '/atom' },
      { name: 'Xcode', link: '/xcode' },
      { name: 'Android Studio', link: '/android-studio' },
      { name: 'GitHub Desktop', link: '/github-desktop' },
      { name: 'IntelliJ IDEA', link: '/intellij-idea' },
      { name: 'Postman', link: '/postman' },
      { name: 'Docker', link: '/docker' },
    ],
  },
  {
    name: 'Productivity',
    tools: [
      { name: 'Notion', link: '/notion' },
      { name: 'Trello', link: '/trello' },
      { name: 'Slack', link: '/slack' },
      { name: 'Google Docs', link: '/google-docs' },
      { name: 'Google Sheets', link: '/google-sheets' },
      { name: 'Apple Calendar', link: '/apple-calendar' },
      { name: 'Chrome', link: '/chrome' },
      { name: 'Gmail', link: '/gmail' },
      { name: 'Google Calendar', link: '/google-calendar' },
      { name: 'Google Meet'},
        { name: 'Microsoft Teams', link: '/microsoft-teams' },
        { name: 'Safari', link: '/safari' },
        { name: 'Zoom', link: '/zoom' },
      ],
  },
  {
    name: 'Operating Systems',
    tools: [
        { name: 'macOS', link: '/macos' },
        { name: 'Windows', link: '/windows' },
        { name: 'Ubuntu', link: '/ubuntu' },
      ],
    },
    {
      name: '3D',
      tools: [
        { name: 'Blender', link: '/blender' }, // Known for extensive shortcuts
        { name: 'Cinema 4D', link: '/cinema-4d' }, // Known for shortcuts
      ],
    },
  ];


  export const shortcuts = {
    figma: {
      categories: [
        {
          name: 'Basic Actions',
          shortcuts: [
            { mac: 'Cmd + D', windows: 'Ctrl + D', description: 'Duplicate selection' },
            { mac: 'Cmd + G', windows: 'Ctrl + G', description: 'Group selection' },
            { mac: 'Cmd + Shift + G', windows: 'Ctrl + Shift + G', description: 'Ungroup selection' },
            { mac: 'Cmd + Z', windows: 'Ctrl + Z', description: 'Undo' },
            { mac: 'Cmd + Shift + Z', windows: 'Ctrl + Shift + Z', description: 'Redo' },
          ],
        },
        {
          name: 'Editing',
          shortcuts: [
            { mac: 'Cmd + X', windows: 'Ctrl + X', description: 'Cut' },
            { mac: 'Cmd + C', windows: 'Ctrl + C', description: 'Copy' },
            { mac: 'Cmd + V', windows: 'Ctrl + V', description: 'Paste' },
            { mac: 'Cmd + Shift + V', windows: 'Ctrl + Shift + V', description: 'Paste in place' },
            { mac: 'Cmd + Option + C', windows: 'Ctrl + Alt + C', description: 'Copy properties' },
            { mac: 'Cmd + Option + V', windows: 'Ctrl + Alt + V', description: 'Paste properties' },
          ],
        },
        {
          name: 'View and Navigation',
          shortcuts: [
            { mac: 'Cmd + 1', windows: 'Ctrl + 1', description: 'Zoom to fit' },
            { mac: 'Cmd + 0', windows: 'Ctrl + 0', description: 'Zoom to 100%' },
            { mac: 'Cmd + +', windows: 'Ctrl + +', description: 'Zoom in' },
            { mac: 'Cmd + -', windows: 'Ctrl + -', description: 'Zoom out' },
            { mac: 'Spacebar + Drag', windows: 'Spacebar + Drag', description: 'Pan' },
          ],
        },
        {
          name: 'Text',
          shortcuts: [
            { mac: 'Cmd + Shift + L', windows: 'Ctrl + Shift + L', description: 'Align text left' },
            { mac: 'Cmd + Shift + T', windows: 'Ctrl + Shift + T', description: 'Align text center' },
            { mac: 'Cmd + Shift + R', windows: 'Ctrl + Shift + R', description: 'Align text right' },
            { mac: 'Cmd + B', windows: 'Ctrl + B', description: 'Bold text' },
            { mac: 'Cmd + I', windows: 'Ctrl + I', description: 'Italicize text' },
          ],
        },
        {
          name: 'Shapes and Objects',
          shortcuts: [
            { mac: 'R', windows: 'R', description: 'Insert rectangle' },
            { mac: 'O', windows: 'O', description: 'Insert ellipse' },
            { mac: 'L', windows: 'L', description: 'Insert line' },
            { mac: 'T', windows: 'T', description: 'Insert text' },
            { mac: 'Shift + Drag', windows: 'Shift + Drag', description: 'Constrain proportions' },
          ],
        },
      ],
    },
    photoshop: {
      categories: [
        {
          name: 'Editing',
          shortcuts: [
            { mac: 'Cmd + Z', windows: 'Ctrl + Z', description: 'Undo' },
            { mac: 'Cmd + Shift + Z', windows: 'Ctrl + Shift + Z', description: 'Redo' },
            { mac: 'Cmd + T', windows: 'Ctrl + T', description: 'Free Transform' },
            { mac: 'Cmd + J', windows: 'Ctrl + J', description: 'Duplicate Layer' },
            { mac: 'Cmd + Shift + J', windows: 'Ctrl + Shift + J', description: 'New Layer via Cut' },
            { mac: 'Cmd + E', windows: 'Ctrl + E', description: 'Merge Layers' },
            { mac: 'Cmd + Shift + E', windows: 'Ctrl + Shift + E', description: 'Merge Visible Layers' },
          ],
        },
        {
          name: 'Selection',
          shortcuts: [
            { mac: 'Cmd + A', windows: 'Ctrl + A', description: 'Select All' },
            { mac: 'Cmd + D', windows: 'Ctrl + D', description: 'Deselect' },
            { mac: 'Cmd + Shift + D', windows: 'Ctrl + Shift + D', description: 'Reselect' },
            { mac: 'Cmd + H', windows: 'Ctrl + H', description: 'Hide Selection Edges' },
            { mac: 'Cmd + Shift + I', windows: 'Ctrl + Shift + I', description: 'Invert Selection' },
          ],
        },
        {
          name: 'View and Navigation',
          shortcuts: [
            { mac: 'Cmd + +', windows: 'Ctrl + +', description: 'Zoom In' },
            { mac: 'Cmd + -', windows: 'Ctrl + -', description: 'Zoom Out' },
            { mac: 'Cmd + 0', windows: 'Ctrl + 0', description: 'Fit to Screen' },
            { mac: 'Cmd + 1', windows: 'Ctrl + 1', description: 'Actual Pixels' },
            { mac: 'Spacebar + Drag', windows: 'Spacebar + Drag', description: 'Pan' },
          ],
        },
        {
          name: 'Tools',
          shortcuts: [
            { mac: 'V', windows: 'V', description: 'Move Tool' },
            { mac: 'M', windows: 'M', description: 'Marquee Tool' },
            { mac: 'L', windows: 'L', description: 'Lasso Tool' },
            { mac: 'W', windows: 'W', description: 'Magic Wand Tool' },
            { mac: 'C', windows: 'C', description: 'Crop Tool' },
            { mac: 'I', windows: 'I', description: 'Eyedropper Tool' },
            { mac: 'B', windows: 'B', description: 'Brush Tool' },
            { mac: 'E', windows: 'E', description: 'Eraser Tool' },
            { mac: 'G', windows: 'G', description: 'Gradient Tool' },
            { mac: 'P', windows: 'P', description: 'Pen Tool' },
            { mac: 'T', windows: 'T', description: 'Type Tool' },
            { mac: 'H', windows: 'H', description: 'Hand Tool' },
          ],
        },
        {
          name: 'Layer Management',
          shortcuts: [
            { mac: 'Cmd + G', windows: 'Ctrl + G', description: 'Group Layers' },
            { mac: 'Cmd + Shift + G', windows: 'Ctrl + Shift + G', description: 'Ungroup Layers' },
            { mac: 'Cmd + Option + G', windows: 'Ctrl + Alt + G', description: 'Create Clipping Mask' },
            { mac: 'Cmd + Option + Shift + G', windows: 'Ctrl + Alt + Shift + G', description: 'Release Clipping Mask' },
            { mac: 'Cmd + Option + A', windows: 'Ctrl + Alt + A', description: 'Select All Layers' },
          ],
        },
        {
          name: 'Brush Adjustments',
          shortcuts: [
            { mac: '[', windows: '[', description: 'Decrease Brush Size' },
            { mac: ']', windows: ']', description: 'Increase Brush Size' },
            { mac: '{', windows: '{', description: 'Decrease Brush Hardness' },
            { mac: '}', windows: '}', description: 'Increase Brush Hardness' },
          ],
        },
        {
          name: 'Blending Modes',
          shortcuts: [
            { mac: 'Shift + Option + N', windows: 'Shift + Alt + N', description: 'Normal' },
            { mac: 'Shift + Option + M', windows: 'Shift + Alt + M', description: 'Multiply' },
            { mac: 'Shift + Option + S', windows: 'Shift + Alt + S', description: 'Screen' },
            { mac: 'Shift + Option + O', windows: 'Shift + Alt + O', description: 'Overlay' },
            { mac: 'Shift + Option + D', windows: 'Shift + Alt + D', description: 'Dissolve' },
          ],
        },
      ],
    },
    sketch: {
      categories: [
        {
          name: 'Inserting Layers',
          shortcuts: [
            { mac: 'A', windows: '', description: 'Insert Artboard' },
            { mac: 'R', windows: '', description: 'Insert Rectangle' },
            { mac: 'O', windows: '', description: 'Insert Oval' },
            { mac: 'U', windows: '', description: 'Insert Rounded Rectangle' },
            { mac: 'T', windows: '', description: 'Insert Text' },
            { mac: 'P', windows: '', description: 'Insert Pencil Tool' },
            { mac: 'V', windows: '', description: 'Insert Vector Tool' },
            { mac: 'L', windows: '', description: 'Insert Line' },
            { mac: 'S', windows: '', description: 'Insert Slice' },
          ],
        },
        {
          name: 'Editing',
          shortcuts: [
            { mac: 'Cmd + C', windows: 'Ctrl + C', description: 'Copy' },
            { mac: 'Cmd + X', windows: 'Ctrl + X', description: 'Cut' },
            { mac: 'Cmd + V', windows: 'Ctrl + V', description: 'Paste' },
            { mac: 'Cmd + Shift + V', windows: 'Ctrl + Shift + V', description: 'Paste Over Selection' },
            { mac: 'Cmd + Z', windows: 'Ctrl + Z', description: 'Undo' },
            { mac: 'Cmd + Shift + Z', windows: 'Ctrl + Shift + Z', description: 'Redo' },
            { mac: 'Cmd + D', windows: 'Ctrl + D', description: 'Duplicate' },
            { mac: 'Cmd + K', windows: 'Ctrl + K', description: 'Scale Layers' },
          ],
        },
        {
          name: 'Arranging Layers',
          shortcuts: [
            { mac: 'Cmd + G', windows: 'Ctrl + G', description: 'Group' },
            { mac: 'Cmd + Shift + G', windows: 'Ctrl + Shift + G', description: 'Ungroup' },
            { mac: 'Cmd + R', windows: 'Ctrl + R', description: 'Rename Layer' },
            { mac: 'Cmd + [', windows: 'Ctrl + [', description: 'Send Backward' },
            { mac: 'Cmd + ]', windows: 'Ctrl + ]', description: 'Bring Forward' },
            { mac: 'Cmd + Option + [', windows: 'Ctrl + Alt + [', description: 'Send to Back' },
            { mac: 'Cmd + Option + ]', windows: 'Ctrl + Alt + ]', description: 'Bring to Front' },
            { mac: 'Cmd + Shift + H', windows: 'Ctrl + Shift + H', description: 'Hide/Show Layer' },
            { mac: 'Cmd + Shift + L', windows: 'Ctrl + Shift + L', description: 'Lock/Unlock Layer' },
          ],
        },
        {
          name: 'View and Navigation',
          shortcuts: [
            { mac: 'Cmd + 0', windows: 'Ctrl + 0', description: 'Zoom to 100%' },
            { mac: 'Cmd + 1', windows: 'Ctrl + 1', description: 'Zoom to Fit Canvas' },
            { mac: 'Cmd + 2', windows: 'Ctrl + 2', description: 'Zoom to Selection' },
            { mac: 'Cmd + 3', windows: 'Ctrl + 3', description: 'Center Selection' },
            { mac: 'Cmd + +', windows: 'Ctrl + +', description: 'Zoom In' },
            { mac: 'Cmd + -', windows: 'Ctrl + -', description: 'Zoom Out' },
            { mac: 'Spacebar + Drag', windows: 'Spacebar + Drag', description: 'Pan Canvas' },
            { mac: 'Option + Cmd + 1', windows: 'Alt + Ctrl + 1', description: 'Show/Hide Layer List' },
            { mac: 'Option + Cmd + 2', windows: 'Alt + Ctrl + 2', description: 'Show/Hide Inspector' },
            { mac: 'Cmd + .', windows: 'Ctrl + .', description: 'Enter Presentation Mode' },
            { mac: 'Ctrl + R', windows: 'Ctrl + R', description: 'Toggle Rulers' },
            { mac: 'Ctrl + G', windows: 'Ctrl + G', description: 'Toggle Grid' },
            { mac: 'Ctrl + L', windows: 'Ctrl + L', description: 'Toggle Layout' },
            { mac: 'Ctrl + P', windows: 'Ctrl + P', description: 'Toggle Pixels on Zoom' },
          ],
        },
        {
          name: 'Text Editing',
          shortcuts: [
            { mac: 'Cmd + B', windows: 'Ctrl + B', description: 'Bold Text' },
            { mac: 'Cmd + I', windows: 'Ctrl + I', description: 'Italicize Text' },
            { mac: 'Cmd + U', windows: 'Ctrl + U', description: 'Underline Text' },
            { mac: 'Cmd + T', windows: 'Ctrl + T', description: 'Change Typeface' },
            { mac: 'Option + Cmd + +', windows: 'Alt + Ctrl + +', description: 'Increase Font Size' },
            { mac: 'Option + Cmd + -', windows: 'Alt + Ctrl + -', description: 'Decrease Font Size' },
            { mac: 'Shift + Cmd + {', windows: 'Shift + Ctrl + {', description: 'Align Left' },
            { mac: 'Shift + Cmd + |', windows: 'Shift + Ctrl + |', description: 'Align Center' },
            { mac: 'Shift + Cmd + }', windows: 'Shift + Ctrl + }', description: 'Align Right' },
            { mac: 'Ctrl + Cmd + Space', windows: 'Ctrl + Alt + Space', description: 'Emoji & Symbols' },
            { mac: 'Cmd + Shift + O', windows: 'Ctrl + Shift + O', description: 'Convert to Outlines' },
          ],
        },
        {
          name: 'Symbols',
          shortcuts: [
            { mac: 'Cmd + Y', windows: 'Ctrl + Y', description: 'Create Symbol' },
            { mac: 'Cmd + Return', windows: 'Ctrl + Enter', description: 'Edit Symbol Source' },
            { mac: 'Cmd + Shift + Y', windows: 'Ctrl + Shift + Y', description: 'Detach from Symbol' },
            { mac: 'Option + Shift + Cmd + Y', windows: 'Alt + Shift + Ctrl + Y', description: 'Detach All Contents from Symbol' },
          ],
        },
      ],
    },
    'adobe-xd': {
    categories: [
      {
        name: 'Tools',
        shortcuts: [
          { mac: 'V', windows: 'V', description: 'Select Tool' },
          { mac: 'R', windows: 'R', description: 'Rectangle Tool' },
          { mac: 'E', windows: 'E', description: 'Ellipse Tool' },
          { mac: 'Y', windows: 'Y', description: 'Polygon Tool' },
          { mac: 'L', windows: 'L', description: 'Line Tool' },
          { mac: 'P', windows: 'P', description: 'Pen Tool' },
          { mac: 'T', windows: 'T', description: 'Text Tool' },
          { mac: 'A', windows: 'A', description: 'Artboard Tool' },
          { mac: 'Z', windows: 'Z', description: 'Zoom Tool' },
          { mac: 'I', windows: 'I', description: 'Eyedropper Tool' },
        ],
      },
      {
        name: 'Editing',
        shortcuts: [
          { mac: 'Cmd + Z', windows: 'Ctrl + Z', description: 'Undo' },
          { mac: 'Cmd + Shift + Z', windows: 'Ctrl + Shift + Z', description: 'Redo' },
          { mac: 'Cmd + X', windows: 'Ctrl + X', description: 'Cut' },
          { mac: 'Cmd + C', windows: 'Ctrl + C', description: 'Copy' },
          { mac: 'Cmd + V', windows: 'Ctrl + V', description: 'Paste' },
          { mac: 'Cmd + D', windows: 'Ctrl + D', description: 'Duplicate' },
          { mac: 'Delete', windows: 'Delete', description: 'Delete' },
          { mac: 'Cmd + A', windows: 'Ctrl + A', description: 'Select All' },
          { mac: 'Cmd + Shift + A', windows: 'Ctrl + Shift + A', description: 'Deselect All' },
        ],
      },
      {
        name: 'File Operations',
        shortcuts: [
          { mac: 'Cmd + N', windows: 'Ctrl + N', description: 'New File' },
          { mac: 'Cmd + O', windows: 'Ctrl + O', description: 'Open File' },
          { mac: 'Cmd + S', windows: 'Ctrl + S', description: 'Save File' },
          { mac: 'Cmd + Shift + S', windows: 'Ctrl + Shift + S', description: 'Save As' },
          { mac: 'Cmd + W', windows: 'Ctrl + W', description: 'Close File' },
          { mac: 'Cmd + Shift + E', windows: 'Ctrl + Shift + E', description: 'Export Batch' },
          { mac: 'Cmd + E', windows: 'Ctrl + E', description: 'Export Selected' },
          { mac: 'Cmd + Shift + I', windows: 'Ctrl + Shift + I', description: 'Import' },
        ],
      },
      {
        name: 'View and Navigation',
        shortcuts: [
          { mac: 'Cmd + 0', windows: 'Ctrl + 0', description: 'Zoom to Fit' },
          { mac: 'Cmd + 1', windows: 'Ctrl + 1', description: 'Zoom to 100%' },
          { mac: 'Cmd + 2', windows: 'Ctrl + 2', description: 'Zoom to 200%' },
          { mac: 'Cmd + 3', windows: 'Ctrl + 3', description: 'Zoom to Selection' },
          { mac: 'Cmd + +', windows: 'Ctrl + +', description: 'Zoom In' },
          { mac: 'Cmd + -', windows: 'Ctrl + -', description: 'Zoom Out' },
          { mac: 'Spacebar', windows: 'Spacebar', description: 'Pan' },
          { mac: 'Cmd + Y', windows: 'Ctrl + Y', description: 'Toggle Layers Panel' },
          { mac: 'Cmd + Shift + Y', windows: 'Ctrl + Shift + Y', description: 'Toggle Assets Panel' },
          { mac: 'Cmd + \'', windows: 'Ctrl + \'', description: 'Show/Hide Square Grid' },
          { mac: 'Cmd + Shift + \'', windows: 'Ctrl + Shift + \'', description: 'Show/Hide Layout Grid' },
          { mac: 'Ctrl + Tab', windows: 'Ctrl + Tab', description: 'Switch between Design and Prototype Mode' },
        ],
      },
      {
        name: 'Text Formatting',
        shortcuts: [
          { mac: 'Cmd + B', windows: 'Ctrl + B', description: 'Bold' },
          { mac: 'Cmd + I', windows: 'Ctrl + I', description: 'Italic' },
          { mac: 'Cmd + U', windows: 'Ctrl + U', description: 'Underline' },
          { mac: 'Cmd + Shift + >', windows: 'Ctrl + Shift + >', description: 'Increase Font Size' },
          { mac: 'Cmd + Shift + <', windows: 'Ctrl + Shift + <', description: 'Decrease Font Size' },
        ],
      },
      {
        name: 'Object Arrangement',
        shortcuts: [
          { mac: 'Cmd + G', windows: 'Ctrl + G', description: 'Group' },
          { mac: 'Cmd + Shift + G', windows: 'Ctrl + Shift + G', description: 'Ungroup' },
          { mac: 'Cmd + K', windows: 'Ctrl + K', description: 'Make Component' },
          { mac: 'Cmd + L', windows: 'Ctrl + L', description: 'Lock/Unlock Layer' },
          { mac: 'Cmd + ;', windows: 'Ctrl + ;', description: 'Show/Hide Guides' },
          { mac: 'Cmd + Shift + ;', windows: 'Ctrl + Shift + ;', description: 'Lock/Unlock Guides' },
          { mac: 'Cmd + R', windows: 'Ctrl + R', description: 'Make Repeat Grid' },
          { mac: 'Cmd + Shift + M', windows: 'Ctrl + Shift + M', description: 'Mask with Shape' },
        ],
      },
      {
        name: 'Alignment and Distribution',
        shortcuts: [
          { mac: 'Cmd + Ctrl + ←', windows: 'Ctrl + Shift + ←', description: 'Align Left' },
          { mac: 'Cmd + Ctrl + C', windows: 'Shift + C', description: 'Align Center Horizontally' },
          { mac: 'Cmd + Ctrl + →', windows: 'Ctrl + Shift + →', description: 'Align Right' },
          { mac: 'Cmd + Ctrl + ↑', windows: 'Ctrl + Shift + ↑', description: 'Align Top' },
          { mac: 'Cmd + Ctrl + M', windows: 'Shift + M', description: 'Align Middle Vertically' },
        ],
      },
    ],
  },
};